from enum import Enum

class PatternVariable(Enum):
    DATE = 'DATE'
    EVENT = 'EVENT'
    CUSTOM_EVENT = 'CUSTOM_EVENT'
    CONTRACT_EVENT = 'CONTRACT_EVENT'
    NORM_EVENT = 'NORM_EVENT'
    SUBJECT = 'SUBJECT'
    VERB_PHRASE = 'VERB_PHRASE'
    IVP = 'IVP'
    TVP = 'TVP'
    LVP = 'LVP'
    TRANSITIVE_VERB = 'TRANSITIVE_VERB'
    LINKING_VERB = 'LINKING_VERB'
    INTRANSITIVE_VERB = 'INTRANSITIVE_VERB'
    ADVERB = 'ADVERB'
    PREP_PHRASE = 'PREP_PHRASE'
    DIRECT_OBJECT = 'DIRECT_OBJECT'
    INDIRECT_OBJECT = 'INDIRECT_OBJECT'
    PREDICATE = 'PREDICATE'
    TIMESPAN = 'TIMESPAN'
    INTERVAL = 'INTERVAL'
    ADV_AND_PP = 'ADV_AND_PP'
    DOBJ_PHRASE = 'DOBJ_PHRASE'
    PRED_PHRASE = 'PRED_PHRASE'


    P_BEFORE_E = 'P_BEFORE_E'
    P_BEFORE_S = 'P_BEFORE_S'
    P_BEFORE_T = 'P_BEFORE_T'
    P_AFTER = 'P_AFTER'
    P_AFTER_E = 'P_AFTER_E'
    P_AFTER_PF = 'P_AFTER_PF'
    P_AFTER_T = 'P_AFTER_T'
    P_AFTER_W = 'P_AFTER_W'
    P_AFTER_I = 'P_AFTER_I'
    P_EXCEPTION = 'P_EXCEPTION'
    P_DURING = 'P_DURING'

    CONDITIONAL_A = 'CONDITIONAL_A'
    CONDITIONAL_T = 'CONDITIONAL_T'
    CONDITIONAL_N = 'CONDITIONAL_N'

    WITHIN = 'WITHIN'
    UNTIL = 'UNTIL'
    NOTICE_EVENT = 'NOTICE_EVENT'
    BETWEEN_TIMEPOINT = 'BETWEEN_TIMEPOINT'
    FROM_TIMEPOINT = 'FROM_TIMEPOINT'
    AND_TIMEPOINT = 'AND_TIMEPOINT'
    UNTIL_TIMEPOINT = 'UNTIL_TIMEPOINT'
    FOR_TIMESPAN = 'FOR_TIMESPAN'
    AFTER_TIMEPOINT = 'AFTER_TIMEPOINT'




